services:
  testDB:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    tmpfs: /var/lib/postgresql

  backend:
    depends_on:
      testDB:
        condition: service_healthy

    build: ../backend
    ports:
      - 4001:4001
    volumes:
      - ../backend/src:/app/src
    env_file:
      - ./.env
    environment:
      - DB_HOST=testDB

  frontend:
    build: ../frontend
    ports:
      - 3000:3000
    volumes:
      - ../frontend/src:/app/src 
    env_file:
      - ./.env
